### ISSUE TITLE
Mostrar estadísticas de centros, ofertas , titulados y candidatos en la página principal

### ISSUE THREAD

**Issue by logongas** [fpempresa/fpempresa#10]
Idear la forma de hacer la web más atractiva a la vista ya que coinciden tanto centros como empresas y titulados en que está tan cerrada a la vista que parece que no se mueve nada dentro de ella y que está abandonada. Con lo que desisten en darse de alta y utilizarla.

- Si soy empresa me interesará saber número de titulados y de que familias profesionales vienen.
- Si soy titulado, me interesa saber empresas dadas de alta, ofertas existentes y familias profesionales de esas ofertas o empresas.
- Si soy centro formativo, me interesará saber cuántos centros formativos existen en la asociación 

Hacer los gráficos parecidos a los del panel de control del administrador.

**Comment by RSginer** [comment]
Hecho en la rama  feature/10-estadisticas

**Comment by logongas** [comment]
No lo veo en develop

**Comment by RSginer** [comment]
7857fec7f8107061179e0fb41a8accf20025b897

**Comment by logongas** [comment]
Se muestran mal el numero de centros: "chartData.numeroEmpresas.length"
Quitar 2 lineas raras:
            $scope.chartData['numeroCentros'] = [{valor: chartData.data.numeroCentros}]
            $scope.chartData['numeroEmpresas'] = [{valor: chartData.data.numeroEmpresas}];
Quitar la gráfica de "Total centros de EmpleaFP" ya que solo hay un único datos!!!!
Quitar la gráfica de "Empresas en EmpleaFP" ya que solo hay un único datos!!!!
