### ISSUE TITLE
A los titulados indicar si no hay ofertas

### ISSUE THREAD

**Issue by logongas** [fpempresa/fpempresa#12]
Cuando como titulado se haga búsqueda de oferta de empleo y no haya del ciclo formativo de la persona que salte un mensaje tipo “No existen ofertas relacionadas con tu ciclo formativo en estos momentos”, algunos centros y titulados llegan a pensar que hacen algo mal ya que no reciben información de ninguna clase cuando no hay ofertas que cumplan ese perfil.

En el propio grid si no hay ningún resultado, que se muestre un mensaje diciendo "Ups. Parece que no hemos encontrado ninguna oferta para ti. Esto es debido a que empleaFP solo muestra ofertas de los ciclos que has cursado ya que desde empleaFP promovemos los ciclos de FP"

**Comment by RSginer** [comment]
Commited in d8d37d4

**Comment by logongas** [comment]
OK
