### ISSUE TITLE
Mostrara las fechas de alta de las oferta

### ISSUE THREAD

**Issue by logongas** [fpempresa/fpempresa#30]
En el grid de las oferta para un alumno, que aparezcan ordenadas por la fecha y que en el propio grid se vea la fecha.

Tambien que en el centro o en la empresa en la pantalla de ver las ofertas, que también aparezcan ordenadas por fechas y que se muestre la fecha de  la oferta

**Comment by logongas** [comment]
Tambien que el administrador que cuando vea ofertas que tambien se vea la fecha y que estén ordenadas de mas recientes a mas antiguas.
Y en el titulado, tanto en la pantalla de ofertas como en las ofertas inscritas.

**Comment by RSginer** [comment]
https://github.com/fpempresa/fpempresa/tree/ofertas-ordenadas

**Comment by RSginer** [comment]
Que el administrador tenga los botones editar y borrar
